# Load the Data Set

In [25]:

import numpy as np
import pandas as pd

In [26]:
df = pd.read_csv("powerplant_data.csv")

In [27]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

# AT => Temperature
# v => Vaccum
# AP => Pressure 
# RH => Humidity

# PE => Produced Energy

In [28]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [29]:
x = df.drop("PE" , axis = 1)
y = df ["PE"]

In [30]:
y.head()

0    480.48
1    445.75
2    438.76
3    453.09
4    464.43
Name: PE, dtype: float64

In [31]:
# Split out data
 
#import sklearn
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [32]:
x_train

         AT      V       AP     RH
5487  25.24  63.47  1011.30  66.21
3522  26.09  70.40  1007.41  85.37
6916  26.63  73.68  1015.15  85.13
7544  32.06  71.85  1007.90  56.44
7600  28.70  71.64  1007.11  69.85
...     ...    ...      ...    ...
5734  26.25  61.02  1011.47  71.22
5191  29.17  64.79  1016.43  61.05
5390  18.00  43.70  1015.40  61.28
860   26.73  68.84  1010.75  66.83
7270   6.40  39.18  1024.60  86.83

[7654 rows x 4 columns]

In [33]:
x_test

         AT      V       AP     RH
2513  29.70  57.35  1005.63  57.35
9411  25.71  71.64  1008.85  77.31
8745  17.83  44.92  1025.04  70.58
9085   9.46  41.40  1026.78  87.58
4950  29.90  64.79  1016.90  48.24
...     ...    ...      ...    ...
7204  20.46  51.43  1010.06  83.79
1599  29.70  67.17  1007.31  66.56
5697  14.64  39.58  1011.46  71.90
350   29.47  71.32  1008.07  67.00
6210  17.70  50.88  1015.44  89.57

[1914 rows x 4 columns]

In [34]:
df.shape

(9568, 5)

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)

x_test_scaled = scaler.transform(x_test)

In [36]:
x_train_scaled

array([[ 0.74805289,  0.72006931, -0.32660017, -0.49711722],
       [ 0.86181948,  1.26515721, -0.98521113,  0.8181501 ],
       [ 0.93409473,  1.52314975,  0.32523844,  0.80167494],
       ...,
       [-0.22097078, -0.834965  ,  0.36756563, -0.83554456],
       [ 0.94747903,  1.14245344, -0.41971997, -0.45455637],
       [-1.77355014, -1.19049131,  1.92520594,  0.91837402]],
      shape=(7654, 4))

In [37]:
x_test_scaled

array([[ 1.34499288,  0.23869298, -1.28658067, -1.10532538],
       [ 0.81095912,  1.36269098, -0.74140656,  0.26485915],
       [-0.2437241 , -0.73900436,  1.99970178, -0.19713193],
       ...,
       [-0.67068342, -1.15902881, -0.29951077, -0.10651852],
       [ 1.31420898,  1.33752097, -0.87346737, -0.44288647],
       [-0.2611237 , -0.27021304,  0.37433797,  1.10646548]],
      shape=(1914, 4))

In [38]:
import torch
import torch.nn as nn

x_train_tensor = torch.tensor(x_train_scaled , dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1,1)

x_test_tensor = torch.tensor(x_test_scaled , dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1,1)

In [39]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
test_dataset = TensorDataset(x_test_tensor, y_test_tensor)

In [40]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

### Deep Learning

In [41]:
# Define our ANN Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            # 1st hidden layer
            nn.Linear(x_train.shape[1], 6),
            nn.ReLU(),
    
            # 2nd hidden layer
            nn.Linear(6, 6),
            nn.ReLU(),
    
            # output layer
            nn.Linear(6, 1),
        )

    def forward(self, x):
        return self.model(x)

In [42]:
import torch.optim as optim

model = ANN()

# loss, optimizer
crietrion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [43]:
# Train the ANN
train_losses = []
val_losses = []

best_val_loss = float("inf")

epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0 # tot training loss for 1 epoch
    
    for xb, yb in train_loader:
        # xb = features of 1 batch
        # yb = labels of 1 batch
        optimizer.zero_grad()
        
        outputs = model(xb) # forward prop....predicted outputs for this batch
        loss = crietrion(outputs, yb) # compute loss
        loss.backward() # back prop.. compute gradients
        optimizer.step() # params update
        
        running_loss += loss.item() # loss is a tensor => py float

    epoch_train_loss = running_loss / len(train_loader)
    train_losses.append(epoch_train_loss)


    # Validation
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad(): # no gradients compute
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = crietrion(outputs, yb)
            running_val_loss += loss

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), "best_model.pt") #.pt or .pth

epoch 1/100 ==> train loss = 205104.3888671875 & val loss = 200592.734375
epoch 2/100 ==> train loss = 185491.22779947918 & val loss = 162694.59375
epoch 3/100 ==> train loss = 128061.567578125 & val loss = 91456.1640625
epoch 4/100 ==> train loss = 61148.50642089844 & val loss = 38320.40234375
epoch 5/100 ==> train loss = 28881.62663574219 & val loss = 23252.439453125
epoch 6/100 ==> train loss = 21014.169576009113 & val loss = 18756.8203125
epoch 7/100 ==> train loss = 17177.98829752604 & val loss = 15146.9013671875
epoch 8/100 ==> train loss = 13626.273295084635 & val loss = 11655.3388671875
epoch 9/100 ==> train loss = 10206.48814086914 & val loss = 8418.2705078125
epoch 10/100 ==> train loss = 7141.747474161783 & val loss = 5640.9130859375
epoch 11/100 ==> train loss = 4652.009627278646 & val loss = 3531.453857421875
epoch 12/100 ==> train loss = 2887.221973164876 & val loss = 2150.699462890625
epoch 13/100 ==> train loss = 1759.6728337605794 & val loss = 1317.03173828125
epoch 14/100 ==> train loss = 1090.8476262410481 & val loss = 829.174560546875
epoch 15/100 ==> train loss = 696.1672596613566 & val loss = 549.3982543945312
epoch 16/100 ==> train loss = 460.363547929128 & val loss = 361.6190185546875
epoch 17/100 ==> train loss = 311.90820201237995 & val loss = 249.4618682861328
epoch 18/100 ==> train loss = 215.01173000335694 & val loss = 170.1809539794922
epoch 19/100 ==> train loss = 149.7458988984426 & val loss = 119.13407135009766
epoch 20/100 ==> train loss = 106.18047828674317 & val loss = 83.66925811767578
epoch 21/100 ==> train loss = 76.15513583819072 & val loss = 60.60444641113281
epoch 22/100 ==> train loss = 57.215776681900024 & val loss = 46.56002426147461
epoch 23/100 ==> train loss = 45.26585107644399 & val loss = 37.554176330566406
epoch 24/100 ==> train loss = 37.41543788512548 & val loss = 32.011207580566406
epoch 25/100 ==> train loss = 32.636776562531786 & val loss = 28.224163055419922
epoch 26/100 ==> train loss = 29.19374089241028 & val loss = 26.0406551361084
epoch 27/100 ==> train loss = 27.03747579008341 & val loss = 24.74346351623535
epoch 28/100 ==> train loss = 25.741262702147164 & val loss = 23.626737594604492
epoch 29/100 ==> train loss = 24.4812993089358 & val loss = 22.58912467956543
epoch 30/100 ==> train loss = 23.70763125816981 & val loss = 22.04654884338379
epoch 31/100 ==> train loss = 23.279359503587088 & val loss = 21.671321868896484
epoch 32/100 ==> train loss = 22.757953568299612 & val loss = 21.24825096130371
epoch 33/100 ==> train loss = 22.408269123236337 & val loss = 20.93802261352539
epoch 34/100 ==> train loss = 22.25899568001429 & val loss = 20.970457077026367
epoch 35/100 ==> train loss = 21.973209923505785 & val loss = 20.68117904663086
epoch 36/100 ==> train loss = 21.920307997862498 & val loss = 20.90354347229004
epoch 37/100 ==> train loss = 21.910498464107512 & val loss = 20.212339401245117
epoch 38/100 ==> train loss = 21.682243957122168 & val loss = 20.1978816986084
epoch 39/100 ==> train loss = 21.602674690882363 & val loss = 20.131563186645508
epoch 40/100 ==> train loss = 21.683567110697428 & val loss = 20.037763595581055
epoch 41/100 ==> train loss = 21.514874962965646 & val loss = 19.95684051513672
epoch 42/100 ==> train loss = 21.444177186489107 & val loss = 19.9975528717041
epoch 43/100 ==> train loss = 21.287535178661347 & val loss = 19.921863555908203
epoch 44/100 ==> train loss = 21.4351780295372 & val loss = 20.39667320251465
epoch 45/100 ==> train loss = 21.36543385187785 & val loss = 21.521240234375
epoch 46/100 ==> train loss = 21.254189737637837 & val loss = 19.667028427124023
epoch 47/100 ==> train loss = 21.374096643924712 & val loss = 19.527856826782227
epoch 48/100 ==> train loss = 21.298037203152976 & val loss = 20.603302001953125
epoch 49/100 ==> train loss = 21.222155368328096 & val loss = 19.73858642578125
epoch 50/100 ==> train loss = 21.11841191848119 & val loss = 19.582332611083984
epoch 51/100 ==> train loss = 21.13548052708308 & val loss = 19.670618057250977
epoch 52/100 ==> train loss = 21.19197224577268 & val loss = 19.797443389892578
epoch 53/100 ==> train loss = 21.118134582042693 & val loss = 19.385221481323242
epoch 54/100 ==> train loss = 21.020783189932505 & val loss = 19.704240798950195
epoch 55/100 ==> train loss = 21.092797183990477 & val loss = 20.84459114074707
epoch 56/100 ==> train loss = 21.0810267051061 & val loss = 19.90336036682129
epoch 57/100 ==> train loss = 21.06742835442225 & val loss = 19.324146270751953
epoch 58/100 ==> train loss = 21.14456901550293 & val loss = 20.266334533691406
epoch 59/100 ==> train loss = 21.156234033902486 & val loss = 19.17220115661621
epoch 60/100 ==> train loss = 21.146715700626373 & val loss = 19.77486228942871
epoch 61/100 ==> train loss = 21.03739606142044 & val loss = 19.171342849731445
epoch 62/100 ==> train loss = 21.134351555506388 & val loss = 20.00098991394043
epoch 63/100 ==> train loss = 21.171948154767353 & val loss = 19.323097229003906
epoch 64/100 ==> train loss = 21.05741855700811 & val loss = 19.21547508239746
epoch 65/100 ==> train loss = 20.840225027004877 & val loss = 19.334978103637695
epoch 66/100 ==> train loss = 20.976109208663306 & val loss = 19.151954650878906
epoch 67/100 ==> train loss = 21.162095975875854 & val loss = 20.267969131469727
epoch 68/100 ==> train loss = 21.081834654013317 & val loss = 20.10109519958496
epoch 69/100 ==> train loss = 20.950030221541724 & val loss = 19.252405166625977
epoch 70/100 ==> train loss = 21.068320882320403 & val loss = 20.42653465270996
epoch 71/100 ==> train loss = 21.13544265429179 & val loss = 19.1727237701416
epoch 72/100 ==> train loss = 20.95019034544627 & val loss = 21.088985443115234
epoch 73/100 ==> train loss = 21.105587430795033 & val loss = 19.2489070892334
epoch 74/100 ==> train loss = 21.129400606950124 & val loss = 20.60247802734375
epoch 75/100 ==> train loss = 20.989435064792634 & val loss = 19.386064529418945
epoch 76/100 ==> train loss = 20.88568400144577 & val loss = 19.17538833618164
epoch 77/100 ==> train loss = 21.004247039556503 & val loss = 19.259801864624023
epoch 78/100 ==> train loss = 21.1891548037529 & val loss = 19.33683967590332
epoch 79/100 ==> train loss = 21.130099387963615 & val loss = 19.885141372680664
epoch 80/100 ==> train loss = 20.927255469560624 & val loss = 19.26275634765625
epoch 81/100 ==> train loss = 20.99244180123011 & val loss = 19.45972442626953
epoch 82/100 ==> train loss = 21.121739892164864 & val loss = 20.079084396362305
epoch 83/100 ==> train loss = 21.11228117545446 & val loss = 19.659523010253906
epoch 84/100 ==> train loss = 20.980600877602896 & val loss = 19.71431541442871
epoch 85/100 ==> train loss = 21.011226757367453 & val loss = 19.565736770629883
epoch 86/100 ==> train loss = 20.919993019104005 & val loss = 19.080669403076172
epoch 87/100 ==> train loss = 21.050360834598543 & val loss = 19.140459060668945
epoch 88/100 ==> train loss = 20.941527005036672 & val loss = 19.938631057739258
epoch 89/100 ==> train loss = 20.89423005580902 & val loss = 19.151105880737305
epoch 90/100 ==> train loss = 20.88842082818349 & val loss = 19.283164978027344
epoch 91/100 ==> train loss = 21.029066216945647 & val loss = 20.101184844970703
epoch 92/100 ==> train loss = 20.920100156466166 & val loss = 19.134294509887695
epoch 93/100 ==> train loss = 20.9071535607179 & val loss = 19.190330505371094
epoch 94/100 ==> train loss = 21.057345859209697 & val loss = 19.44072914123535
epoch 95/100 ==> train loss = 21.020072603225707 & val loss = 18.978721618652344
epoch 96/100 ==> train loss = 20.905192210276923 & val loss = 19.49036979675293
epoch 97/100 ==> train loss = 20.85960469643275 & val loss = 19.510400772094727
epoch 98/100 ==> train loss = 20.98236456712087 & val loss = 19.38780403137207
epoch 99/100 ==> train loss = 20.886144026120505 & val loss = 19.166492462158203
epoch 100/100 ==> train loss = 20.900553699334463 & val loss = 19.59294319152832

In [44]:
import matplotlib.pyplot as plt 

loss_df = pd.DataFrame({
     "Training Loss": train_losses,
     "Validation Loss" :val_losses

})

plt.plot(loss_df["Training Loss "] , label = " Training Loss")
plt.plot(loss_df[" Validation Loss"] , label = " Validation Loss")

plt.xlabel

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
import matplotlib.pyplot as plt

loss_df = pd.DataFrame({
    "Training Loss": train_losses,
    "Validation Loss": val_losses
})

plt.plot(loss_df["Training Loss"], label = "Training Loss")
plt.plot(loss_df["Validation Loss"], label = "Validation Loss")

plt.xlabel("Epochs")
plt.ylabel("Losses")

plt.legend()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# Loading the best model
model.load_state_dict(torch.load("best_model.pt"))

In [ ]:
import torch.nn as nn

class ANNModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(4, 6),   # matches [6,4]
            nn.ReLU(),
            nn.Linear(6, 6),   # matches [6,6]
            nn.ReLU(),
            nn.Linear(6, 1)    # matches [1,6]
        )

    def forward(self, x):
        return self.model(x)

In [55]:
model = ANNModel()
state_dict = torch.load("best_model.pt")

print("Model keys:", model.state_dict().keys())
print("Saved keys:", state_dict.keys())

Model keys: odict_keys(['model.0.weight', 'model.0.bias', 'model.2.weight', 'model.2.bias', 'model.4.weight', 'model.4.bias'])
Saved keys: odict_keys(['model.0.weight', 'model.0.bias', 'model.2.weight', 'model.2.bias', 'model.4.weight', 'model.4.bias'])

In [47]:
predicted_df = pd.DataFrame(test_preds.numpy(), columns=["Predicted Values"])
actual_df = pd.DataFrame(y_test.values, columns=["Actual Values"])

pd.concat([predicted_df, actual_df], axis=1)

      Predicted Values  Actual Values
0           435.809845         433.27
1           437.769104         438.16
2           461.984680         458.42
3           477.107819         480.82
4           435.892456         441.41
...                ...            ...
1909        452.115387         456.70
1910        432.328125         438.04
1911        468.218842         467.80
1912        431.802826         437.14
1913        457.339355         456.78

[1914 rows x 2 columns]

In [52]:
print(type(torch.load("best_model.pt")))

<class 'collections.OrderedDict'>

In [53]:
model = ANNModel()
model.load_state_dict(torch.load("best_model.pt"))
model.eval()

RuntimeError: Error(s) in loading state_dict for ANNModel:
	size mismatch for model.0.weight: copying a param with shape torch.Size([6, 4]) from checkpoint, the shape in current model is torch.Size([16, 4]).
	size mismatch for model.0.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for model.2.weight: copying a param with shape torch.Size([6, 6]) from checkpoint, the shape in current model is torch.Size([8, 16]).
	size mismatch for model.2.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for model.4.weight: copying a param with shape torch.Size([1, 6]) from checkpoint, the shape in current model is torch.Size([1, 8]).

In [54]:
state_dict = torch.load("best_model.pt")

for key in state_dict:
    print(key, state_dict[key].shape)

model.0.weight torch.Size([6, 4])
model.0.bias torch.Size([6])
model.2.weight torch.Size([6, 6])
model.2.bias torch.Size([6])
model.4.weight torch.Size([1, 6])
model.4.bias torch.Size([1])

In [56]:
torch.save(model, "full_model.pt")